name: Build Desktop app

on:
  push:
    branches: [main]
    paths:
      - composeApp/**
      - gradle/**
      - gradle.properties
      - settings.gradle.kts
      - build.gradle.kts
      - .github/workflows/build-desktop.yml
  pull_request:
    paths:
      - composeApp/**
      - gradle/**
      - gradle.properties
      - settings.gradle.kts
      - build.gradle.kts
      - .github/workflows/build-desktop.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Desktop Compile (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Set up Gradle cache
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Desktop compile
        run: ./gradlew :composeApp:compileKotlinDesktop --stacktrace --build-cache
